create table application_properties (id integer generated by default as identity, change_date timestamp, down_payment_percentage integer not null, entrance_fee_adult double not null, entrance_fee_child double not null, max_adult_per_booking integer not null, max_children_per_booking integer not null, primary key (id))
create table guest (id integer generated by default as identity, contact_number varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), primary key (id))
create table miscellaneous (id integer generated by default as identity, code varchar(255), description varchar(255), name varchar(255), rate double not null, primary key (id))
create table payment (id integer generated by default as identity, mode varchar(255), reference_id varchar(255), remarks varchar(255), reservation_ref_id varchar(255), status varchar(255), total_amount double not null, transaction_type varchar(255), primary key (id))
create table payment_item (id integer generated by default as identity, amount double not null, description varchar(255), payment_id integer, primary key (id))
create table reservation (id integer generated by default as identity, check_in timestamp, check_out timestamp, count_adult integer not null, count_children integer not null, extra_charge_amount double not null, extra_charge_description varchar(255), reference_id varchar(255), remarks varchar(255), status varchar(255), total_amount double not null, type varchar(255), main_guest_id integer, primary key (id))
create table reservation_amenities (reservation_id integer not null, amenities_id integer not null)
create table role (id integer generated by default as identity, code varchar(255), description varchar(255), name varchar(255), primary key (id))
create table room (id integer generated by default as identity, capacity integer not null, code varchar(255), description varchar(255), name varchar(255), rate double not null, status varchar(255), type varchar(255), primary key (id))
create table room_type (id integer generated by default as identity, name varchar(255), primary key (id))
create table user (id integer generated by default as identity, contact_number varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(60), status varchar(255), user_name varchar(255), primary key (id))
create table user_roles (user_id integer not null, roles_id integer not null)
alter table payment_item add constraint FK2n2y0k5ju4e1bndwikq8igyj2 foreign key (payment_id) references payment
alter table reservation add constraint FK11om6qsmuqin9298xxgwcyali foreign key (main_guest_id) references guest
alter table reservation_amenities add constraint FK2x94yj42oocn2bs443bf6088y foreign key (amenities_id) references miscellaneous
alter table reservation_amenities add constraint FK9991awode8px2i6opovln9udi foreign key (reservation_id) references reservation
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user
